# Generated by Django 5.2.6 on 2025-09-03 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='unsubsribed_at',
            new_name='unsubscribed_at',
        ),
    ]
