# Generated by Django 5.2.6 on 2025-09-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_rename_unsubsribed_at_subscriber_unsubscribed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='resubscribed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
